#!/usr/bin/env python3
"""
Automated API Baseline Testing Script
Generated by API Discovery Engine

This script validates all discovered endpoints against their contracts.
"""

import asyncio
import json
import sys
from typing import Dict, List
import httpx
import pytest
from datetime import datetime

class BaselineTestResult:
    def __init__(self):
        self.passed = []
        self.mock_validated = []
        self.not_implemented = []
        self.failed = []
        self.total_endpoints = 0

class APIBaselineTester:
    def __init__(self, base_url: str = "http://localhost:8000"):
        self.base_url = base_url
        self.client = httpx.AsyncClient()
        self.results = BaselineTestResult()
    
    async def run_baseline_tests(self, endpoints_file: str) -> BaselineTestResult:
        """Run baseline tests for all endpoints"""
        with open(endpoints_file, 'r') as f:
            endpoints_data = json.load(f)
        
        endpoints = endpoints_data['endpoints']
        self.results.total_endpoints = len(endpoints)
        
        print(f"Running baseline tests for {len(endpoints)} endpoints...")
        
        try:
            for endpoint in endpoints:
                await self._test_endpoint(endpoint)
            return self.results
        finally:
            try:
                await self.client.aclose()
            except Exception:
                print('Warning: failed to close AsyncClient')
    
    async def _test_endpoint(self, endpoint: Dict):
        """Test a single endpoint"""
        try:
            url = f"{self.base_url}{endpoint['path']}"
            method = endpoint['method'].lower()
            
            # Make request
            if method == 'get':
                response = await self.client.get(url)
            elif method == 'post':
                response = await self.client.post(url, json={})
            elif method == 'put':
                response = await self.client.put(url, json={})
            elif method == 'delete':
                response = await self.client.delete(url)
            else:
                response = await self.client.request(method.upper(), url)
            
            # Categorize result
            if response.status_code == 404:
                self.results.not_implemented.append({
                    'endpoint': endpoint,
                    'status_code': response.status_code,
                    'error': 'Endpoint not found'
                })
            elif response.status_code == 200:
                # Check for mock header
                if response.headers.get('X-Data-Source') == 'MOCK':
                    self.results.mock_validated.append({
                        'endpoint': endpoint,
                        'status_code': response.status_code,
                        'response_size': len(response.content)
                    })
                else:
                    self.results.passed.append({
                        'endpoint': endpoint,
                        'status_code': response.status_code,
                        'response_size': len(response.content)
                    })
            else:
                self.results.failed.append({
                    'endpoint': endpoint,
                    'status_code': response.status_code,
                    'error': response.text[:200]
                })
                
        except Exception as e:
            self.results.failed.append({
                'endpoint': endpoint,
                'status_code': 0,
                'error': str(e)
            })
    
    def generate_report(self, output_file: str):
        """Generate baseline test report"""
        report = {
            'metadata': {
                'generated_at': datetime.now().isoformat(),
                'total_endpoints': self.results.total_endpoints,
                'base_url': self.base_url
            },
            'summary': {
                'passed': len(self.results.passed),
                'mock_validated': len(self.results.mock_validated),
                'not_implemented': len(self.results.not_implemented),
                'failed': len(self.results.failed)
            },
            'details': {
                'passed': self.results.passed,
                'mock_validated': self.results.mock_validated,
                'not_implemented': self.results.not_implemented,
                'failed': self.results.failed
            }
        }
        
        with open(output_file, 'w') as f:
            json.dump(report, f, indent=2)
        
        print(f"\nBaseline Test Report Generated: {output_file}")
        print(f"PASSED: {len(self.results.passed)}")
        print(f"MOCK_VALIDATED: {len(self.results.mock_validated)}")
        print(f"NOT_IMPLEMENTED: {len(self.results.not_implemented)}")
        print(f"FAILED: {len(self.results.failed)}")

async def main():
    if len(sys.argv) != 2:
        print("Usage: python baseline_test.py <endpoints.json>")
        sys.exit(1)
    
    endpoints_file = sys.argv[1]
    tester = APIBaselineTester()
    results = await tester.run_baseline_tests(endpoints_file)
    tester.generate_report('baseline_test_report.json')

if __name__ == "__main__":
    asyncio.run(main())
